### ISSUE TITLE
Evolved Template gets wonky

### ISSUE THREAD

**Issue by Zukibird** [Heliomance/HeroForge-Anew#76] opened 2016-02-18 23:45 UTC
If you apply the Evolved Template just once it calculates OK. But the +2 bonuses to STR and CHA go to +8 each on the second addition of the Evolved template and I think it was +18 on each if you add it a third time. Also it repeats the spell like abilities on the character sheet once for each evolved template added (ie cone of cold, contagion, greater dispel magic, cone of cold, contagion, greater dispel magic, cone of cold, contagion, greater dispel magic) and Fast Heal and Natural armor do not increase each time.

**Comment by ThAlEdison** [comment] 2016-02-18 23:54
I noticed this myself. It's doing double adding, inside of the templateinfo
sheet it is calculating values based on the number of evolved templates
(likely from an older version of the sheet). The current version of the
sheet then adds these again as part of its normal template stacking.

**Comment by torrasque666** [comment] 2016-06-29 08:06
Its a simple fix, probably some artifact from an earlier version. Most of those problems are caused by a variable in the stat blocks called EvolvedCount. Either make that a binary variable (1/0, T/F) or just remove them all.

The Spell likes.... I got nothing.

**Comment by TwistedFaith84** [comment] 2016-06-29 15:08
It could also be coming from the Name Manager for Formulas (which should be gone through to help ride of the older versions) but thats just a guess.

**Comment by Heliomance** [comment] 2017-05-02 11:00
**Fixed in 8.0.**

**Closed as completed by Heliomance** 2017-05-02 11:00 UTC
Labels: bug
