### ISSUE TITLE
Temp Mods on Character Sheet 1 mostly working

### ISSUE THREAD

**Issue by TwistedFaith84** [Heliomance/HeroForge-Anew#11] opened 2015-03-15 20:07 UTC
The Temp Con Mod isn't affecting HP thought I think it is affecting Fort save. Temp Str Mod isn't affecting attack bonus damage. I not sure about the others. I noticed it at last gaming session with my group when I got hit by a fang spider and failed my fort.

**Comment by Heliomance** [comment] 2015-03-16 13:26
Couldn't reproduce the strength issue, it's working fine for me. Con not affecting hit points... that's a tricky one. The calculation of HP is quite complicated, especially now I've added wildshape (which changes your Con without changing your HP). I'll have a think about how best to fix that.

**Comment by TwistedFaith84** [comment] 2015-03-17 08:28
I thought their was an issue with the Str. I could be mistaken I'll double check my character.

**Comment by Heliomance** [comment] 2015-03-17 13:04
Fixed in v7.4.0.0. I've made temp con affect your HP except when in Wildshape or a Hengeyokai in animal form.

**Closed as completed by Heliomance** 2015-03-17 13:04 UTC
