### ISSUE TITLE
Ranger: pets, bugs and drama

### ISSUE THREAD

**Issue by zerkeros** [Heliomance/HeroForge-Anew#21] opened 2015-04-26 23:10 UTC
Hello I play a Ranger, Rogue, Order of the Bow Initiate hybrid and thus I ran into a few problems.
1) Wild Empathy die roll is inaccurate. Normally, it's 1d20 + CHA Mod + Ranger lvl.
    In my case it should be 1d20 + 5, since I have +0 CHA Mod and I'm only 5 lvl Ranger, yet it shows       1d20 + 7.

2) Favored enemy. I have chosen only 2 favored enemies aaaaand......_ctrl c - ctrl v_
Favored Enemy: "blah blah blah"
- Undead (+2 bonus)
- Humanoid (elf) (+4 bonus)
- (+4 bonus)
- (+4 bonus)
- (+4 bonus)
- (+4 bonus)
  .............

3) My Pet's (Eagle) skills and stats are incorrect. I compared them with Monster Manual's correct ones and it's like day and night differences!

**Comment by TwistedFaith84** [comment] 2015-04-27 18:34
Which version are you using? The UNSTABLE v7.3.2.4 that was upped about 20 days ago or the last STABLE v7.3.2.3 that was upped last February sometime?

1) The Wild Empathy is most likely because you get a +2 bonus for having >5 ranks in Handle animal

2) Favored Enemy idk probably a mess up in the code somewhere.

3) Your pet you might be better off doing it by hand or using the 3.5 Animal Companion sheet found here https://github.com/TwistedFaith84/DND_Gaming_Tools/blob/master/3.5%20Animal%20Companion%20v8.3.xls [Click on RAW button to download] At least till the Animal Companion Sheet gets figured out.

**Comment by zerkeros** [comment] 2015-04-28 11:22
1) you are right i had handle animal +5
2) :-/ that sucks
3) thanx for that

btw i am using the "STABLE v7.3.2.3 that was upped last February sometime"

**Comment by Zukibird** [comment] 2016-08-18 12:36
Hey TwistedFaith84! Can you please repost the animal companion worksheet? The link above isn't working...

**Comment by TwistedFaith84** [comment] 2016-08-18 18:38
Yeah sorry I kinda deleted my GitHub cause it was a little to complicated for me to upload anything and I'm pretty good with computers. I have a Dropbox for all that stuff now and here is the link to that.

https://www.dropbox.com/sh/9n4crdfvrc10bz1/AADDbxznLSwiwxJgUO1bmVVma?dl=0

In here you'll find all the stuff that came from NZComputers along with some others that I got from other places.

**Comment by Heliomance** [comment] 2017-04-26 10:14
Could not reproduce any issues in the current dev version of the sheet. As I've made changes to both Favoured Enemy and Animal Companions since the last release, I'm inclined to think I fixed this incidentally. Closing as **fixed in 8.0**.

**Closed as completed by Heliomance** 2017-04-26 10:14 UTC
Labels: bug
